INSERT INTO game_store.companies(company_name, country_origin, ceo, logo)
VALUES ('Ubisoft', 'France', 'Yves Guillemot', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.FUYoCXi-MHQd69OGgGIVYAHaFS%26pid%3DApi&f=1'),
		('Bethesda', 'USA', 'Christopher Weaver', 'https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.bagofgames.com%2FDevelopment2%2Fwp-content%2Fuploads%2F2015%2F02%2Fdownload.png&f=1&nofb=1');
	
INSERT INTO game_store.video_games(game_name, company_name, release_date, logo)
VALUES ('Overwatch', 'Activision Blizzard', '2016-05-24', 'https://duckduckgo.com/i/570c284a.jpg'),
		('MLB the Show 21', 'Sony', '2021-20-4', 'https://duckduckgo.com/i/4b1d95e7.jpg'),
		('Fortnite', 'Epic Games', '2017-07-21', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.mobygames.com%2Fimages%2Fcovers%2Fl%2F567948-fortnite-battle-royale-nintendo-switch-front-cover.jpg&f=1&nofb=1'),
		('Mystery Case Files: MillionHeir', 'Big Fish Games', '2008-09-08', 'https://imgix.ranker.com/node_img/1650/32992468/original/mystery-case-files-millionheir-video-games-photo-1?auto=format&fit=crop&fm=pjpg&crop=faces&h=125&w=125&q=60&dpr=1'),
		('Destiny', 'Bungie', '2014-09-14', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.UnwAwE_BcdCC8z5LDPmmCQHaHa%26pid%3DApi&f=1'),
		('Destiny 2', 'Bungie', '2017-09-06', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.5U_o2DwJrIyggvShI4kfhwHaHa%26pid%3DApi&f=1'),
		('Rayman Origins', 'Ubisoft', '2011-11-15', 'https://duckduckgo.com/i/0554a6b2.jpg'),
		('Rayman Legends', 'Ubisoft', '2014-02-18', 'https://duckduckgo.com/i/273235a0.jpg'),
		('Fallout 3', 'Bethesda', '2008-10-28', 'https://upload.wikimedia.org/wikipedia/en/8/83/Fallout_3_cover_art.PNG'),
		('Fallout 4', 'Bethesda', '2015-11-10', 'https://upload.wikimedia.org/wikipedia/en/7/70/Fallout_4_cover_art.jpg'),
		('Fallout: New Vegas', 'Bethesda', '2010-10-19', 'https://upload.wikimedia.org/wikipedia/en/3/34/Fallout_New_Vegas.jpg'),
		('Doom Eternal', 'Bethesda', '2020-03-20', 'https://upload.wikimedia.org/wikipedia/en/9/9d/Cover_Art_of_Doom_Eternal.png');
		
INSERT INTO game_store.genres(genre_name)
VALUES 
		('Stealth'),
		('Fighting'),
		('Survival'),
		('Survival Horror'),
		('Battle Royale'),
		('Text'),
		('Interactive Movie'),
		('MMORPG'),
		('Tactical Role-Playing'),
		('Sandbox Role-Playing'),
		('Strategy'),
		('Role-Playing'),
		('Simulation'),
		('Party'),
		('Puzzle'),
		('Trivia'),
		('Sports'),
		('Board'),
		('Racing'),
		('First Person Shooter'),
		('Tactical FPS'),
		('Rhythm'),
		('Platformer'),
		('Educational'),
		('Bulletstorm'),
		('Tower Defense'),
		('Historical'),
		('Science Fiction'),
		('Futuristic'),
		('Turn Based'),
		('2D Fighting'),
		('3D Fighting'),
		('2D Platformer'),
		('3D Platformer'),
		('Shooting'),
		('Third Person Shooter'),
		('Adventure'),
		('Action-Adventure');
